-- SAT Tutor Pro: Initial Schema Migration

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Student profile
CREATE TABLE students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  parent_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  settings JSONB DEFAULT '{}'
);

-- Skill ratings (one row per sub-skill per student)
CREATE TABLE skill_ratings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  sub_skill_id TEXT NOT NULL,
  elo_rating INTEGER DEFAULT 1000,
  questions_attempted INTEGER DEFAULT 0,
  questions_correct INTEGER DEFAULT 0,
  is_calibrated BOOLEAN DEFAULT FALSE,
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, sub_skill_id)
);

-- Question passages (for reading questions)
CREATE TABLE passages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  passage_id TEXT UNIQUE NOT NULL,
  passage_text TEXT NOT NULL,
  passage_type TEXT, -- literary_fiction, social_science, natural_science, humanities
  word_count INTEGER,
  source TEXT
);

-- Questions bank
CREATE TABLE questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id TEXT UNIQUE NOT NULL,
  source TEXT NOT NULL,
  section TEXT NOT NULL CHECK (section IN ('math', 'reading_writing')),
  sub_skill_id TEXT NOT NULL,
  difficulty INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
  question_text TEXT NOT NULL,
  passage_id TEXT REFERENCES passages(passage_id),
  answer_choices JSONB NOT NULL,
  correct_answer TEXT NOT NULL,
  distractor_analysis JSONB,
  is_ai_generated BOOLEAN DEFAULT FALSE,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Session log
CREATE TABLE sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  session_type TEXT NOT NULL CHECK (session_type IN ('quick_drill', 'study_session', 'timed_section', 'full_practice_test', 'review')),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  questions_answered INTEGER DEFAULT 0,
  questions_correct INTEGER DEFAULT 0,
  accuracy FLOAT,
  summary TEXT,
  mood_signals JSONB DEFAULT '[]',
  sub_skills_practiced TEXT[] DEFAULT '{}',
  sub_skill_focus TEXT,
  metadata JSONB DEFAULT '{}'
);

-- Individual question attempts (core analytics table)
CREATE TABLE question_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  session_id UUID REFERENCES sessions(id) ON DELETE CASCADE,
  question_id TEXT REFERENCES questions(question_id),
  student_answer TEXT NOT NULL,
  is_correct BOOLEAN NOT NULL,
  time_spent_seconds INTEGER,
  confidence_level TEXT CHECK (confidence_level IN ('guessing', 'okay', 'confident')),
  error_type TEXT CHECK (error_type IN ('conceptual_gap', 'procedural_error', 'careless_rush', 'misread_comprehension', 'trap_answer', 'time_pressure', 'knowledge_gap')),
  distractor_type TEXT CHECK (distractor_type IN ('partial_answer', 'sign_error', 'misapplied_formula', 'scope_error', 'sounds_right', 'wrong_variable', 'other')),
  error_explanation TEXT,
  explanation_strategy_used TEXT,
  attempted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Spaced repetition queue
CREATE TABLE review_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  question_id TEXT REFERENCES questions(question_id),
  next_review_date DATE NOT NULL,
  review_count INTEGER DEFAULT 0,
  last_review_result BOOLEAN,
  interval_days INTEGER DEFAULT 1,
  UNIQUE(student_id, question_id)
);

-- Pattern recognition insights (generated by Opus)
CREATE TABLE wrong_answer_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  total_wrong_answers_analyzed INTEGER,
  top_insights JSONB NOT NULL,
  dimension_details JSONB NOT NULL,
  raw_analysis TEXT
);

-- Score predictions
CREATE TABLE score_predictions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  predicted_at TIMESTAMPTZ DEFAULT NOW(),
  total_score_low INTEGER,
  total_score_mid INTEGER,
  total_score_high INTEGER,
  rw_score INTEGER,
  math_score INTEGER,
  confidence FLOAT
);

-- Daily streak tracking
CREATE TABLE daily_activity (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  activity_date DATE NOT NULL,
  questions_answered INTEGER DEFAULT 0,
  streak_qualifying BOOLEAN DEFAULT FALSE,
  UNIQUE(student_id, activity_date)
);

-- Weekly goals
CREATE TABLE weekly_goals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  goals JSONB NOT NULL DEFAULT '[]',
  progress JSONB NOT NULL DEFAULT '{}',
  UNIQUE(student_id, week_start)
);

-- Indexes for performance
CREATE INDEX idx_skill_ratings_student ON skill_ratings(student_id);
CREATE INDEX idx_question_attempts_student ON question_attempts(student_id);
CREATE INDEX idx_question_attempts_session ON question_attempts(session_id);
CREATE INDEX idx_sessions_student ON sessions(student_id);
CREATE INDEX idx_review_queue_student ON review_queue(student_id);
CREATE INDEX idx_review_queue_date ON review_queue(student_id, next_review_date);
CREATE INDEX idx_daily_activity_student ON daily_activity(student_id);
CREATE INDEX idx_questions_skill ON questions(sub_skill_id);
CREATE INDEX idx_questions_difficulty ON questions(difficulty);
CREATE INDEX idx_wrong_answer_insights_student ON wrong_answer_insights(student_id);

-- Row Level Security
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE wrong_answer_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE score_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_goals ENABLE ROW LEVEL SECURITY;

-- RLS Policies (students can only see their own data)
CREATE POLICY "Students can view own data" ON students FOR SELECT USING (auth.uid()::text = id::text);
CREATE POLICY "Students can update own data" ON students FOR UPDATE USING (auth.uid()::text = id::text);

CREATE POLICY "Students can view own skill ratings" ON skill_ratings FOR ALL USING (auth.uid()::text = student_id::text);
CREATE POLICY "Students can view own sessions" ON sessions FOR ALL USING (auth.uid()::text = student_id::text);
CREATE POLICY "Students can view own attempts" ON question_attempts FOR ALL USING (auth.uid()::text = student_id::text);
CREATE POLICY "Students can view own review queue" ON review_queue FOR ALL USING (auth.uid()::text = student_id::text);
CREATE POLICY "Students can view own insights" ON wrong_answer_insights FOR ALL USING (auth.uid()::text = student_id::text);
CREATE POLICY "Students can view own predictions" ON score_predictions FOR ALL USING (auth.uid()::text = student_id::text);
CREATE POLICY "Students can view own activity" ON daily_activity FOR ALL USING (auth.uid()::text = student_id::text);
CREATE POLICY "Students can view own goals" ON weekly_goals FOR ALL USING (auth.uid()::text = student_id::text);

-- Questions and passages are public read
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE passages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Questions are publicly readable" ON questions FOR SELECT USING (true);
CREATE POLICY "Passages are publicly readable" ON passages FOR SELECT USING (true);
